db:
  build: ./MySQL/5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root4321  
  volumes:
    - ./MySQL/5.7/volumes:/var/lib/mysql

apache:
  build: ./apache-php7
  ports:
    - "80:80"
    - "443:433"
  volumes:
    - ./magento/2.1.6/store:/var/www/html
  links:
    - db
